name: CI/CD Pipeline for NuxtJS

# Chạy workflow khi có push hoặc pull request vào nhánh 'main'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout để lấy mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Thiết lập Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Cài đặt dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Chạy ESLint để kiểm tra tính hợp lệ của mã
      - name: Run ESLint
        run: npm run lint

      # Step 5: Chạy kiểm thử với Jest (nếu có)
      - name: Run tests
        run: npm test

      # Step 6: Build dự án NuxtJS
      - name: Build project
        run: npm run build

  cd:
    runs-on: ubuntu-latest
    needs: ci
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
